### ISSUE TITLE
Why is it still very easy to trigger even though I have already set the threshold to the maximum?

### ISSUE THREAD

**Issue by wwjCMP** [1C0D/obsidian-easy-toggle-sidebars#10]
Why is it still very easy to trigger even though I have already set the threshold to the maximum?

![Snipaste_2023-10-03_22-11-36](https://github.com/1C0D/obsidian-easy-toggle-sidebars/assets/32979859/d2002710-4423-4013-9456-e2dd33da6d33)

**Comment by 1C0D** [comment]
thks for having reported
version 1.2.2 fixed
