### ISSUE TITLE
Give option to disable pinning tabs

### ISSUE THREAD

**Issue by tim-hilde** [1C0D/obsidian-easy-toggle-sidebars#11]
Please give an option to disable the tab pinning behavior introduced last release

**Comment by caasion** [comment]
+1; it doesn't only happen when you double click on the tab header, but anywhere in the document. 

It's becoming very annoying since almost every tab is pinned.

**Comment by 1C0D** [comment]
@caasion  wait it's an option that I added. I will make it optional. but why are you double clicking on tabs anyway? is it another function that you are using?

**Comment by 1C0D** [comment]
oh I see there is a bug it was meant to only work when double clicking on a tab header. but I will make it optional anyway

**Comment by 1C0D** [comment]
ok, there was a total mess in the way I auto updated my versions numbers. So you didn't get the last release. Ok now it's working, only toggling pin when double-clicking on a tab header. And I made it optional, which is better.
