### ISSUE TITLE
Feature Request: Use right mouse button

### ISSUE THREAD

**Issue by Ampa** [1C0D/obsidian-easy-toggle-sidebars#2]
Great idea for a plugin - thank you.

I am used to opening side panels in Vivaldi with right mouse button and swipe right / left.

I wonder if this plugin could offer this as an alternative?

**Comment by 1C0D** [comment]
I considered doing this when doing the plugin, but the right click is opening the context menu. So I don't see how to do it.
And BTW I have just installed it to check and right click is opening the context menu too.

**Comment by Ampa** [comment]
OK, that is a shame that it can't work.

**Comment by 1C0D** [comment]
Right mouse button have been enabled. click+ move and double click.

**Comment by 1C0D** [comment]
I have to add options in settings...
Can you tell me how it feels using only right click ?

**Comment by Ampa** [comment]
Another great update. Thanks.
