### ISSUE TITLE
Double middle click does not work if only one side panel is open.

### ISSUE THREAD

**Issue by Ampa** [1C0D/obsidian-easy-toggle-sidebars#3]
Double middle click does not work if only one side panel is open.

I would expect it to close any open panels, and a second double click to return to the previous state Left / Right / Both panels.

Thanks for the useful plugin.

**Comment by 1C0D** [comment]
ok thks for having reported this. fixed

**Comment by Ampa** [comment]
Wow! Awesome. Thank you.
