### ISSUE TITLE
Feature Request: Having a hotkey to activate the command instead of middle click

### ISSUE THREAD

**Issue by nhan000** [1C0D/obsidian-easy-toggle-sidebars#4]
Obsidian weirdly has a hotkey to toggle right *or* left sidebar, but not both at the same time. Was wondering if you could implement it with your plugin?

Thanks a lot for making this plugin! This is what I've been looking for a long time.

**Comment by 1C0D** [comment]
Command "Toggle both sidebars" added. So you can add your own shortcut to it.
