### ISSUE TITLE
Feature Request: Generalize to become a Mouse Gestures plugin?

### ISSUE THREAD

**Issue by Ampa** [1C0D/obsidian-easy-toggle-sidebars#5]
Hi 1C0D,

Do you think it would be possible to generalize this to become a Mouse Gestures plugin? And would you have any interest in doing so?

In my browser I constantly use mouse gestures to Close and Reopen Tabs, Toggle Fullscreen, go Forward and Back through the History, etc. It would be very powerful to do the same in Obsidian. I suppose the ultimate version would allow a user specified gesture, to be assigned to any command in Obsidian.

**Comment by 1C0D** [comment]
This one is hard. Not sure to have the level to do this at the moment.

**Comment by Ampa** [comment]
No problem.

Just thought I'd ask, but absolutely no pressure. Very happy with what you've done already.
