### ISSUE TITLE
Middle double click won't close sidebars when in a Canvas

### ISSUE THREAD

**Issue by daxmonson** [1C0D/obsidian-easy-toggle-sidebars#6]
Works fine closing sidebars when in a normal note, but not when in a Canvas. Would be cool if it worked there too since those benefit from a wide visual overview. Great plugin btw.

**Comment by 1C0D** [comment]
I added a vertical move, so you can do this from the ribbon bar and the double click there too. The middle-click is better there, because with right-click the menu is opened.
