### ISSUE TITLE
Auto toggle and graph view

### ISSUE THREAD

**Issue by pozh** [1C0D/obsidian-easy-toggle-sidebars#7]
Nice extension, thanks! I've just installed your recent update and noticed an unexpected behaviour while drowsing my graph view: when I click a tag in it, I expect to see that tag revealed in the sidebar - search results pane, but the new option of your ext hides the sidebar right away. I guess the "auto hide" options requires some exceptions to be added.

**Comment by 1C0D** [comment]
should be ok now about canvas graph view title header and tags...
explanations should appear when updating

**Comment by pozh** [comment]
thanks! 👍
